# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Where
        run: cd C:\apps\ ; ls
      - name: show
        run: ls
      - name: show2
        run: |
          $username = "gmejia"
          $password = ConvertTo-SecureString "Vorealis123*" -AsPlainText -Force
          $credential = New-Object System.Management.Automation.PSCredential($username, $password)
          Start-Process -FilePath "cmd.exe" -ArgumentList "/c `"%windir%\syswow64\inetsrv\appcmd start site `"rtsol.e2f.stg.vorealis.com`"`"" -Credential $credential
