name: CI

on:
  # Triggers the workflow on push or pull request events but only for the "staging" 
  push:
    branches: [ "staging" ]
  pull_request:
    branches: [ "staging" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


jobs:
  
  build:
    
    runs-on: self-hosted
    
    steps:
      - name: Stop sites in IIS
        run: cmd.exe /c "C:\apps\e2f-stag\stop-all-sites.bat"
      - name: Make Pull from github repository
        run: cmd.exe /c "C:\apps\e2f-stag\make-pull.bat"
      - name: Generar PRACT
        run: cmd.exe /c "C:\apps\e2f-stag\stag-generar_pract.bat"
      - name: Generar PRSOL
        run: cmd.exe /c "C:\apps\e2f-stag\stag-generar_prsol.bat"
      - name: Generar RTCAL
        run: cmd.exe /c "C:\apps\e2f-stag\stag-generar_rtcal.bat"
      - name: Generar RTSOL
        run: cmd.exe /c "C:\apps\e2f-stag\stag-generar_rtsol.bat"
      - name: Start sites in IIS
        run: cmd.exe /c "C:\apps\e2f-stag\start-all-sites.bat"
      - name: Despliegue completado en staging
        run: echo "Despligue completo"
